services:
  backend:
    build: ./backend
    container_name: organic-backend
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env.production
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: organic-redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: organic-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
